### ISSUE TITLE
refactoring support broken

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#159]
<pre>
$ python refactor.py rename Contribution:haskellCabal Contribution:haskellEngineer
Wikisername: rlaemmel
Password: 
[u'Language:Haskell', u'101companies:System', u'Feature:Total', u'Feature:Cut', u'Technology:GHC', u'Module', u'Feature:Flatness', u'Contribution:haskellList', u'Contribution:haskellStarter', u'Theme:Haskell introduction', u'Contribution:haskellWhere', u'Contribution:haskellLambda', u'Feature:Closed serialization'] Contribution:haskellEngineer
Traceback (most recent call last):
  File "refactor.py", line 56, in <module>
    commands[sys.argv[1]](titles, flags)
  File "refactor.py", line 17, in dorename
    p.intermove(mvto=titles[1], **flags)
  File "/Users/laemmel/projects/101dev/tools/wikiRefactoring/page2.py", line 129, in intermove
    self.rewriteReferences(self.getBacklinks(), mvto)
  File "/Users/laemmel/projects/101dev/tools/wikiRefactoring/page2.py", line 40, in rewriteReferences
    page.rewriteInternlink(self.title, newtitle)
  File "/Users/laemmel/projects/101dev/tools/wikiRefactoring/page2.py", line 83, in rewriteInternlink
    self.edit(text=ntext)
  File "build/bdist.macosx-10.3-fat/egg/wikitools/page.py", line 538, in edit
  File "build/bdist.macosx-10.3-fat/egg/wikitools/api.py", line 139, in query
  File "build/bdist.macosx-10.3-fat/egg/wikitools/api.py", line 214, in __getRaw
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
</pre>

**Comment by tschmorleiz** [comment]
Essentially the MediaWiki API is down (http://mediawiki.101companies.org/wiki/api.php). Looking into this with @avaranovich .

**Comment by tschmorleiz** [comment]
Should be back up, please check and close if it works for you.
